// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Response struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type User struct {
	ID        int    `json:"Id"`
	Firstname string `json:"Firstname"`
	Lastname  string `json:"Lastname"`
	Username  string `json:"Username"`
}
